# Generated by Django 5.0.1 on 2024-02-06 03:31

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField()),
                ("curr", models.CharField(max_length=3)),
                ("price", models.FloatField()),
                ("publish_date", models.DateField()),
                ("query_date", models.DateField()),
                ("rate", models.FloatField()),
                ("tableNo", models.CharField()),
                (
                    "pricePLN",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("rate"), "*", models.F("price")
                        ),
                        output_field=models.FloatField(),
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="authors", to="books.author"
                    ),
                ),
            ],
            options={
                "ordering": ["-query_date"],
            },
        ),
    ]
