# Generated by Django 5.0.1 on 2024-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_rename_modelname_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="query_date",
            field=models.DateTimeField(),
        ),
    ]
